// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: h4/h4.proto

package h4

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	H4_Request_FullMethodName = "/h4.h4/Request"
	H4_Reply_FullMethodName   = "/h4.h4/Reply"
)

// H4Client is the client API for H4 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type H4Client interface {
	Request(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (*ReplyMessage, error)
	Reply(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (*ReplyMessage, error)
}

type h4Client struct {
	cc grpc.ClientConnInterface
}

func NewH4Client(cc grpc.ClientConnInterface) H4Client {
	return &h4Client{cc}
}

func (c *h4Client) Request(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (*ReplyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplyMessage)
	err := c.cc.Invoke(ctx, H4_Request_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *h4Client) Reply(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (*ReplyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplyMessage)
	err := c.cc.Invoke(ctx, H4_Reply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// H4Server is the server API for H4 service.
// All implementations must embed UnimplementedH4Server
// for forward compatibility.
type H4Server interface {
	Request(context.Context, *RequestMessage) (*ReplyMessage, error)
	Reply(context.Context, *RequestMessage) (*ReplyMessage, error)
	mustEmbedUnimplementedH4Server()
}

// UnimplementedH4Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedH4Server struct{}

func (UnimplementedH4Server) Request(context.Context, *RequestMessage) (*ReplyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedH4Server) Reply(context.Context, *RequestMessage) (*ReplyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reply not implemented")
}
func (UnimplementedH4Server) mustEmbedUnimplementedH4Server() {}
func (UnimplementedH4Server) testEmbeddedByValue()            {}

// UnsafeH4Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to H4Server will
// result in compilation errors.
type UnsafeH4Server interface {
	mustEmbedUnimplementedH4Server()
}

func RegisterH4Server(s grpc.ServiceRegistrar, srv H4Server) {
	// If the following call pancis, it indicates UnimplementedH4Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&H4_ServiceDesc, srv)
}

func _H4_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(H4Server).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: H4_Request_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(H4Server).Request(ctx, req.(*RequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _H4_Reply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(H4Server).Reply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: H4_Reply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(H4Server).Reply(ctx, req.(*RequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// H4_ServiceDesc is the grpc.ServiceDesc for H4 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var H4_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "h4.h4",
	HandlerType: (*H4Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _H4_Request_Handler,
		},
		{
			MethodName: "Reply",
			Handler:    _H4_Reply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "h4/h4.proto",
}
